REM INSERTING into C##TEST.TEACHER
SET DEFINE OFF;
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10500','张颖','123123','中国上海','zhangyin@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10501','袁时金','123123',null,'yuanshijin@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10502','唐剑蜂','123123',null,'tangjianfeng@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10503','朱亚萍','123123',null,'zhuyaping@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10514','石硕','123123',null,'ss@tongji.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10508','邹杰','123123',null,'zoujie@fuzhong.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10509','周金赫','123123',null,'zjh@fuzhong.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10510','李翔宇','123123',null,'lxy@163.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10511','汪佳玲','123123',null,'wjl@fuzhong.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10513','黄长水','123123',null,'hcs@tongji.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10518','贾金原','123123',null,'Jae@tj.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10506','罗烨','123123',null,'luoye@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10507','韩风夏','123123',null,'hanfengxia@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10517','唐悠悠','123123',null,'tyy@aqgy.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10519','赵宪忠','123123',null,'zxz@tj.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10520','陈荣','123123',null,'cr@tj.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10521','龙家林','123123',null,'ljl@163.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10522','张林','123123',null,'zl@tj.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10523','王冬青','123123',null,'wdq@tj.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10504','史杨','123123',null,'shiyang@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10516','徐左','123123',null,'xz@tj.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10505','赵清佩','123123',null,'zhaoqingpei@tongji.edu.cn');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10512','续忠斌','123123',null,'xzb@163.com');
Insert into C##TEST.TEACHER (ID,NAME,PASSWORD,LOCATION,EMAIL) values ('10515','钟声','123123',null,'zs@tongji.com');
